// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery', 'underscore', 'backbone', 'questionview', 'summaryview'], function($, _, Backbone, QuestionView, SummaryView) {
    var AppView;
    return AppView = Backbone.View.extend({
      el: $("#testApp"),
      currentPos: 0,
      correct: 0,
      currentQuestionView: null,
      questions: null,
      answers: null,
      responses: null,
      nextQuestion: function() {
        var sumView;
        if (this.currentQuestionView !== null) {
          this.currentQuestionView.undelegateEvents();
          this.responses.add(this.currentQuestionView.response);
          if (this.currentQuestionView.response.isCorrect()) {
            this.correct++;
          }
        }
        this.currentPos++;
        if (this.currentPos < (this.questions.length + 1)) {
          this.currentQuestionView = new QuestionView({
            appView: this,
            question: this.questions.get(this.currentPos),
            answer: this.answers.get(this.currentPos)
          });
          return this.currentQuestionView.render();
        } else {
          this.currentQuestionView.hide();
          sumView = new SummaryView({
            totalQuestions: this.questions.length,
            correct: this.correct
          });
          return sumView.render();
        }
      },
      initialize: function(options) {
        this.questions = options.questions;
        this.answers = options.answers;
        this.responses = options.responses;
        return this.nextQuestion();
      }
    });
  });

}).call(this);
