// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    var SummaryView;
    return SummaryView = Backbone.View.extend({
      template: "<h1>Test Complete</h1><fieldset><legend>Test Results:</legend><div><%=correct%> correct out of <%=totalQuestions%></div></fieldset>",
      el: $("#summary"),
      totalQuestions: 0,
      correct: 0,
      initialize: function(options) {
        this.totalQuestions = options.totalQuestions;
        return this.correct = options.correct;
      },
      render: function() {
        var data;
        data = {
          correct: this.correct,
          totalQuestions: this.totalQuestions
        };
        return this.$el.html(_.template(this.template, data));
      }
    });
  });

}).call(this);
